### ISSUE TITLE
Link to sibling blocks in block overview

### ISSUE THREAD

**Issue by Sword-Smith** [Neptune-Crypto/neptune-explorer#2]
The block overview should indicate if there are other blocks known with the same height. I've added an endpoint for this in `neptune-core` in f5ee1b04cdad2ce208e2ccab7ca61ce18c7e46d1. The block explorer can just link to the other blocks with the same height.

I suggest that we just add a new field to the `BlockInfoHtmlPage` named e.g. `sibling_blocks`, like so:

```rust
pub struct BlockInfoHtmlPage<'a> {
        header: HeaderHtml<'a>,
        block_info: BlockInfo,
        sibling_blocks: Vec<Digest>
    }
```

That list of digests would be empty if only one block at that height is known. And a link to the sibiling blocks should be provided.And some info should be provided if the block you're currently viewing is not part of the canonical chain.

**Comment by dan-da** [comment]
sounds good.

> And some info should be provided if the block you're currently viewing is not part of the canonical chain

yeah, I'm thinking just adding a simple field to the page:

In canonical chain:  yes|no

**Comment by dan-da** [comment]
Presently the /block page only makes a single RPC call to neptune-core to the /block_info endpoint.  Calling block_digests_by_height() would double that to 2 requests per page.

Since we agreed to display only a boolean "in canonical chain" on the page, I have optimized by adding an is_canonical boolean field to the block_info result.   in 3995e39d6612e0cd7bd3a075e4eff50c205e47d5.   So we can continue with just 1 RPC call per page.

**Comment by dan-da** [comment]
hmm, I forgot about:

> The block explorer can just link to the other blocks with the same height.

So for now we may just make the 2nd RPC call.   Alternative is to add the sibling blocks data to the BlockInfo struct returned by /block_info endpoint.
